POST /api/stationaryItem/save
Host: localhost:8080
Content-Type: application/json
Accept: application/json

{

    "itemName": "pen",
    "quantity": 25,
    "returnable": true
}

###

GET /api/stationaryItem/4
Host: localhost:8080
Accept: application/json

###

GET /api/stationaryItem
Host: localhost:8080
Accept: application/json

###

PATCH  /api/stationaryItem/2
Host: localhost:8080
Content-Type: application/json
Accept: application/json


{
    "returnable":"true"
}

###

DELETE /api/stationaryItem/2
Host: localhost:8080
Accept: application/json


###

POST /api/admin/register
Host: localhost:8080
Content-Type: application/json

{
    "adminName":"admin5",
    "adminEmail":"admin5@xmple.com",
    "adminPassword":"123456"
}

###
GET /api/admin
Host: localhost:8080
Accept: application/json

###
POST /api/admin/login
Host: localhost:8080
Content-Type: application/json

{ 
    "adminEmail": "admin6@xmple.com",
    "adminPassword":"123456"
}

###

POST /api/student/register
Host: localhost:8080
Content-Type: application/json

{
    "studentName":"student8",
    "studentEmail":"student8@xmple.com",
    "studentPassword":"123456"
}

###

POST /api/student/login
Host: localhost:8080
Content-Type: application/json

{
   "studentEmail":"student8@xmple.com",
    "studentPassword":"123456"
}

###

GET /api/student
Host: localhost:8080
Accept: application/json

###