POST /api/stationaryItem/save
Host: localhost:8080
Content-Type: application/json
Accept: application/json

{

    "itemName": "eraser",
    "quantity": 100,
    "returnable": true
}

###

GET /api/stationaryItem/6
Host: localhost:8080
Accept: application/json

###

GET /api/stationaryItem
Host: localhost:8080
Accept: application/json

###

PATCH  /api/stationaryItem/5
Host: localhost:8080
Content-Type: application/json
Accept: application/json


{
   "quantity": 100,
    "returnable": true
}

###

DELETE /api/stationaryItem/2
Host: localhost:8080
Accept: application/json


###

POST /api/admin/register
Host: localhost:8080
Content-Type: application/json

{
    "adminName":"admin9",
    "adminEmail":"admin9@xmple.com",
    "adminPassword":"123456"
}

###
GET /api/admin
Host: localhost:8080
Accept: application/json

###
POST /api/admin/login
Host: localhost:8080
Content-Type: application/json

{ 
    "adminEmail": "admin9@xmple.com",
    "adminPassword":"123456"
}

###

POST /api/student/register
Host: localhost:8080
Content-Type: application/json

{
    "studentName":"student3",
    "studentEmail":"student3@xmple.com",
    "studentPassword":"123456"
}

###


GET /api/student
Host: localhost:8080
Accept: application/json

###

POST /api/student/login
Host: localhost:8080
Content-Type: application/json

{
   "studentEmail":"student3@xmple.com",
    "studentPassword":"123456"
}

###

POST /api/transaction/4
Host: localhost:8080
Content-Type: application/json

{
    "stationaryItemId":"2",
    "withdrawnQuantity":35,
    "returnDate":"2023-07-20",
    "returned":"false"
}        

###


Get /api/transaction
Host: localhost:8080
Content-Type: application/json

###  

#get by transactionId
Get /api/transaction/3
Host: localhost:8080
Content-Type: application/json
Accept: application/json

###

#get All by studentId
Get /api/transaction/all/byStudentId?id=1
Host: localhost:8080
Content-Type: application/json
Accept: application/json

###

#get All by studentId
Get /api/transaction/all/byItemId?id=2
Host: localhost:8080
Content-Type: application/json
Accept: application/json

###



PATCH /api/transaction/2
Host: localhost:8080
Content-Type: application/json
Accept: application/json

{
    "transactionId":6,
    "returnDate":"2023-07-25",
    "returned": true
}

###      
